### ISSUE TITLE
[FEATURE] Run jupyter doc notebooks in headless mode to notice outdatedness

### ISSUE THREAD

**Issue by nikita-galileo** [rungalileo/dataquality#224]
### Is your feature request related to a problem

When we push updates to the dataquality client's interface we may forget that downstream our docs and notebooks will break. At least in this repo we have a notebook or two that should be kept updated with the code syntax so we have some source of truth on client usage.

### The solution you would like

Run the jupyter notebook in a headless mode to check it still is able to successfully complete. We could also add maybe some assertions to the bottom to actually turn it into a real test

**Comment by Ben-Epstein** [comment]
we do this for our colab notebooks now
